### ISSUE TITLE
Meteor server crashes if gRPC endpoint is down

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/qrl-wallet#28]
```
I20171025-07:57:01.550(11)? Error fetching qrl.proto from localhost:9009
W20171025-07:57:01.552(11)? (STDERR) /Users/scottdonald/repos/qrl/scottdonaldau/qrl-wallet/.meteor/local/build/programs/server/app/app.js:151
W20171025-07:57:01.552(11)? (STDERR)     fs.writeFile(qrlProtoFilePath, res.grpcProto, function (err) {
W20171025-07:57:01.553(11)? (STDERR)                                       ^
W20171025-07:57:01.554(11)? (STDERR)
W20171025-07:57:01.555(11)? (STDERR) TypeError: Cannot read property 'grpcProto' of undefined
W20171025-07:57:01.555(11)? (STDERR)     at Object.callback (imports/startup/server/index.js:49:36)
W20171025-07:57:01.555(11)? (STDERR)     at /Users/scottdonald/repos/qrl/scottdonaldau/qrl-wallet/node_modules/grpc/src/node/src/client.js:557:12
=> Exited with code: 1
=> Meteor server restarted
```

**Comment by scottdonaldau** [comment]
It also appears timeouts to a node will result in localhost connection attempts, and eventually meteor server failure.

**Comment by scottdonaldau** [comment]
#30 Fixed.
