### ISSUE TITLE
[UI] when sending QRL pre-filled fields do not transfer value to form

### ISSUE THREAD

**Issue by ubidefeo** [theQRL/qrl-wallet#54]
you have to manually specify 0 for __fee__ and __OTS key__
```javascript
I20171105-22:28:54.634(1)? Exception while invoking method 'transferCoins' Error: Illegal value for xmss_ots_indexvalue element of type uint64: string (empty string)
I20171105-22:28:54.635(1)?     at fail (/Users/ubi/qrl-wallet/node_modules/protobufjs/dist/protobuf.js:1817:23)
I20171105-22:28:54.636(1)?     at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/Users/ubi/qrl-wallet/node_modules/protobufjs/dist/protobuf.js:1857:29)
I20171105-22:28:54.636(1)?     at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/ubi/qrl-wallet/node_modules/protobufjs/dist/protobuf.js:3499:33)
I20171105-22:28:54.636(1)?     at MessagePrototype.set (/Users/ubi/qrl-wallet/node_modules/protobufjs/dist/protobuf.js:2493:59)
I20171105-22:28:54.636(1)?     at MessagePrototype.set (/Users/ubi/qrl-wallet/node_modules/protobufjs/dist/protobuf.js:2483:38)
I20171105-22:28:54.636(1)?     at new Message (/Users/ubi/qrl-wallet/node_modules/protobufjs/dist/protobuf.js:2411:34)
I20171105-22:28:54.636(1)?     at serialize (/Users/ubi/qrl-wallet/node_modules/grpc/src/node/src/protobuf_js_5_common.js:66:23)
I20171105-22:28:54.637(1)?     at ServiceClient.Client.makeUnaryRequest (/Users/ubi/qrl-wallet/node_modules/grpc/src/node/src/client.js:515:17)
I20171105-22:28:54.637(1)?     at apply (/Users/ubi/qrl-wallet/node_modules/lodash/lodash.js:499:17)
I20171105-22:28:54.637(1)?     at ServiceClient.wrapper [as transferCoins] (/Users/ubi/qrl-wallet/node_modules/lodash/lodash.js:5356:16)
```

**Comment by scottdonaldau** [comment]
Hi @ubidefeo We are working on a solution to OTS key management, which is covered in https://github.com/theQRL/qrl-wallet/issues/35

I'll keep this issue open to implement a default fee for transactions.

**Comment by scottdonaldau** [comment]
Default values are new prefilled as 'value' rather than 'placeholder'.
